### ISSUE TITLE
LEAP service unavailable

### ISSUE THREAD

**Issue by zanyim** [TeamLeap/leapapp#50]
LEAP offline capability

**Comment by felily** [comment]
Still in progress - Im having bug . the problem is the status error, its not the same as the error ExceptionError that the ESB it growing

**Comment by felily** [comment]
ready for testing

**Comment by felily** [comment]
The screen goes to next screen even the server is wrong

**Comment by felily** [comment]
The bug has been fixed , the code is working

**Comment by tshekopulego** [comment]
This issue was resolved
