### ISSUE TITLE
Deploy LEAP Services in PROD

### ISSUE THREAD

**Issue by zanyim** [TeamLeap/leapapp#53]

**Comment by Mohapi27** [comment]
Deployment Guide in progress.

**Comment by Mohapi27** [comment]
Service tested in QA. Production deployment sent to Matimba, waiting for confirmation once deployment is done.

**Comment by Mohapi27** [comment]
Waiting for CAB from Molema.

**Comment by Mohapi27** [comment]
Change log documents submitted to relevant team.
