### ISSUE TITLE
Error Handling (HR)

### ISSUE THREAD

**Issue by zanyim** [TeamLeap/leapapp#54]

**Comment by MthunziDuze** [comment]
Get connection for HR on dev
Modify error handling code

**Comment by MthunziDuze** [comment]
connection is up
Update the adapters
Configure services to use the new adapters

**Comment by MthunziDuze** [comment]
Error Handling fixed, and tested, 
Expected Error Response:
{
  "error": {
    "error": "com.wm.pkg.art.error.DetailedServiceException",
    "description": "[ART.117.4002] Adapter Runtime (Adapter Service): Unable to invoke adapter service EMMHR.adapters:getDepartmentList.\n[ART.118.5013] Adapter Runtime (Connection): Unable to find connection EMMConnections.JDBC.HR:HR."
  }
}

from both services.
